nextcloud:
  host: cloud1.rootedinfra.site
  username: admin
  password: admin123
  datadir: /var/www/html/data

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: cloud1.rootedinfra.site
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cloud1-tls
      hosts:
        - cloud1.rootedinfra.site
